name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: docker compose -f docker-compose-build.yaml build --parallel
    - run: docker tag udagram-frontend:local antokazungu/udagram-frontend
    - run: docker tag udagram-api-feed antokazungu/udagram-api-feed
    - run: docker tag udagram-api-user antokazungu/udagram-api-user
    - run: docker tag reverseproxy antokazungu/reverseproxy
    - run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --pas
    - run: push antokazungu/udagram-frontend
    - run: push antokazungu/udagram-api-feed
    - run: push antokazungu/udagram-api-user
    - run: push antokazungu/reverseproxy
