name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: docker compose -f docker-compose-build.yaml build --parallel
    - run: docker tag udagram-frontend:local antokazungu/udagram-frontend
    - run: docker tag udagram-api-feed antokazungu/udagram-api-feed
    - run: docker tag udagram-api-user antokazungu/udagram-api-user
    - run: docker tag reverseproxy antokazungu/reverseproxy
    - run: echo "${{ secrets.DOCKERPW }}" | docker login -u "antokazungu" --password-stdin
    - run: docker push antokazungu/udagram-frontend:latest
    - run: docker push antokazungu/udagram-api-feed:latest
    - run: docker push antokazungu/udagram-api-user:latest
    - run: docker push antokazungu/reverseproxy:latest
